### ISSUE TITLE
Built-in `<UserProfile />` component is only responsive to screen, not container.

### ISSUE THREAD

**Issue by ksmithut** [clerk/javascript#4920]
### Preliminary Checks

- [x] I have reviewed the documentation: https://clerk.com/docs

- [x] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [x] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [x] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/ksmithut/clerk-responsive-bug

### Publishable key

pk_test_Zmxvd2luZy1uZXd0LTUwLmNsZXJrLmFjY291bnRzLmRldiQ

### Description

This is just using the prebuilt `<UserProfile />` component. It appears to be responsive based on screen size rather than the container size. This becomes apparent when you have static nav on the left side of the page and make the browser window smaller.

Here is what it looks like at "full" width:

<img width="1382" alt="Image" src="https://github.com/user-attachments/assets/650477ba-0dce-4330-aa51-00a90bd75c4d" />

Here's when part of it gets cut off (notice the "Update Profile" is cut off:

<img width="1016" alt="Image" src="https://github.com/user-attachments/assets/ed20b6ab-447a-4d15-9b10-dbc3f43caad8" />

Here's when it moves components down due do the screen size (but things are still cut off):

<img width="962" alt="Image" src="https://github.com/user-attachments/assets/57298e18-511d-4e66-89ed-6bc004f29312" />

**Expected behavior:**

I would expect the component to be responsive based on the container size, not the screen size.

**Actual behavior:**

The component is only responsive based on screen size.

### Environment

```Shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M1
    Memory: 476.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.6.0 - ~/.local/share/mise/installs/node/23.6.0/bin/node
    npm: 10.9.2 - ~/.local/share/mise/installs/node/23.6.0/bin/npm
    bun: 1.1.43 - ~/.local/share/mise/installs/bun/1.1.43/bin/bun
    Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 18.2
  npmPackages:
    @clerk/clerk-react: ^5.21.3 => 5.21.3
    @vitejs/plugin-react: ^4.3.4 => 4.3.4
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    vite: ^6.0.5 => 6.0.7
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The functionality you're asking for is called [Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries). We can't use it for our components as we support older browsers and the functionality can't be polyfilled.

You can customize our components to implement this on your own if the browser support is OK for you: https://clerk.com/docs/customization/overview

**Comment by ksmithut** [comment]
For anyone who finds this issue, here's the CSS that worked for me, though it may be missing something:

```css

.user-profile-container {
  container-type: inline-size;
}

.cl-userProfile-root {
  width: 100%;
}

.cl-userProfile-root .cl-cardBox {
  width: 100%;
}

/* sm */
@container (max-width: 30em) {
  .cl-userProfile-root .cl-profileSection {
    flex-direction: column-reverse;
    gap: 0.5rem;
  }
}

/* md */
@contianer (max-width: 48em) {
  .cl-userProfile-root .cl-navbar {
    display: none;
  }
  .cl-userProfile-root .cl-navbarMobileMenuRow {
    display: flex;
  }
  .cl-userProfile-root .cl-cardBox {
    display: flex;
    flex-direction: column;
  }
}

/* lg */
@container (max-width: 62em) {
  .cl-userProfile-root .cl-profileSection {
    flex-direction: column-reverse;
    gap: 0.5rem;
  }
  .cl-userProfile-root .cl-profileSectionHeader {
    align-self: self-start;
    margin-top: unset;
    transform: none;
    padding: 0px;
  }
}
```
